### ISSUE TITLE
Don't update dependencies with only a patch version change

### ISSUE THREAD

**Issue by Imtnt** [fastify/fastify-formbody#7]
npm by default allows patch version updates to happen transparently. When you update the fastify version, fastify checks itself for incompatible version numbers. Therefore, if I depend on both this package and fastify, I will randomly get messages like this:

  `Error: fastify-plugin - expected '>=1.0.0-rc.1' fastify version, '0.39.1' is installed`

Incompatible (really any) dependency version updates MUST be included in something larger than a patch release. 

On a side note, is an update to an RC build really necessary in the first place?

**Comment by delvedor** [comment]
Checkout https://github.com/fastify/fastify/issues/763

**Comment by jsumners** [comment]
Yes it is necessary -- https://github.com/fastify/fastify/issues/763

Dependency updates that do not break the published API of the module are not MAJOR or MINOR updates. This will only be a problem during the `v1.0.0-rc` phase of Fastify. Indeed, this plugin should not see any other updates until `v1.0.0` is final. And my intention is do issue a new MAJOR at that time simply due to the fact that Fastify will then be at a stable, LTS, version.

**Comment by mcollina** [comment]
@jsumners how about you remove https://github.com/fastify/fastify-formbody/blob/master/formbody.js#L52 completely until 1.0.0 is out?
I think that should have been a major change on its own.

**Comment by jsumners** [comment]
Done and published as v1.2.5.
